#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [ -x ~/.config/bspwm/dual_monitor_script ];then
    ~/.config/bspwm/dual_monitor_script
fi

bspc config border_width	1

bspc config window_gap          3

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Polybar launch - with support for multiple monitors
~/.config/polybar/./launch.sh

# Wallpaper (with feh)
feh --bg-fill ~/Pictures/Wallpapers/baby_mandalorian_yoda.jpg

# Enable mouse focus-follow
bspc config focus_follows_pointer true

bspc config border_width 2
xsetroot -cursor_name left_ptr &


# battery check
# upower -i /org/freedesktop/UPower/devices/battery_BAT1
