#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.

if [ -x /home/santiago/.config/bspwm/dual_monitor_script ];then
    /home/santiago/.config/bspwm/dual_monitor_script
fi

#bspc monitor HMDI-1-1 -d 1 2 3 4 5
#bspc monitor eDP-1-1 -d 6 7 8 9 0

bspc config border_width	1

bspc config window_gap          3

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Polybar for laptop monitor
/home/santiago/.config/polybar/./launch.sh

# Fondo de pantalla (with feh)
feh --bg-fill /home/santiago/Pictures/Wallpapers/baby_mandalorian_yoda.jpg

# If HDMI monitor, launch polybar
# hmdi_monitor=$(xrandr -q | grep 'HDMI-1-1')

# Para que siga al mouse
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 2
xsetroot -cursor_name left_ptr &


# battery check
# upower -i /org/freedesktop/UPower/devices/battery_BAT1
