#!/usr/bin/env bash

# set up the two monitors for bspwm

# para saber como se llama cada uno de los monitores correr el comando
# xrandr -q | grep -w connected
# alli se muestra el nombre de cada uno de los monitores conectados

# detecto si hay un HDMI
my_laptop_external_monitor=$(xrandr --query | grep ' connected')
external_monitor=$(xrandr --query | grep ' connected' | cut -d " " -f1 | grep HDMI)

# laptop mon
laptop_mon=$(xrandr -q | grep " connected" | cut -d ' ' -f1 | grep eDP*)

# si hay un HDMI lo hago primario
# por default el HDMI esta a la izquierda de la notebook
# si estuviera a la derecha cambiar '--left-of --> --right-of'
# se configura como primario al HDMI
if [[ $external_monitor = *HDMI* ]]; then
	xrandr --output $laptop_mon --primary --mode 1920x1080 --rotate normal --output $external_monitor --mode 1920x1080 --rotate normal --left-of $laptop_mon
	#bspc monitor $external_monitor -d 1 2 3 4 5
	#bspc monitor $laptop_mon -d 6 7 8 9 0
	bspc monitor $laptop_mon -d 1 2 3 4 5
	bspc monitor $external_monitor -d 6 7 8 9 0
else
	xrandr --output $laptop_mon --primary --mode 1920x1080 --rotate normal
	bspc monitor $laptop_mon -d 1 2 3 4 5 6 7 8 9 0
fi
